#!/usr/bin/env bash

# Make a backup of the default config file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Edit the default config file to add a redirect location
sudo sed -i '/server_name _;/a \
	location /redirect_me { \
		return 301 https://www.example.com/redirect_destination; \
	}' /etc/nginx/sites-available/default

# Restart the nginx service
sudo service nginx restart
